[ingestor]
id     = esp32_ingestor
plugin = ./AP_plugin.so

[script]
id      = prom_exporter
runtime = python
path    = ./scripts/prometheus_exporter.py
trigger = esp32_raw
emits   = prometheus_metrics

[publisher]
id           = prom_http
type         = http
host         = 0.0.0.0
port         = 8080          # <-- CHANGED: was 9090, now 8080
path         = /metrics
content_type = text/plain; version=0.0.4; charset=utf-8

[routes]
esp32_raw          = prom_exporter
prometheus_metrics = prom_http
telemetry = telemetry